version: '3'

services:
  broker:
    image: redis:alpine
    volumes:
      - broker_data:/data

  worker:
    build: worker
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - broker

  stresser:
    build: stresser
    volumes:
      - ./src:/app
    depends_on:
      - broker

  supervisor:
    build: supervisor
    volumes:
      - ./src:/app
    depends_on:
      - broker
    ports:
      - 5555:5555

volumes:
  broker_data:
