version: '3'

services:
  broker:
    image: redis:alpine
    volumes:
      - broker_data:/data

  worker_a:
    build: worker
    volumes:
      - ./src:/app
    environment:
      - WORKER_CONCURRENCY=2
      - WORKER_LOGLEVEL=info
      - WORKER_NAME=my_worker
      - WORKER_QUEUE=queue1
    depends_on:
      - broker

  worker_b:
    build: worker
    volumes:
      - ./src:/app
    environment:
      - WORKER_CONCURRENCY=2
      - WORKER_LOGLEVEL=info
      - WORKER_NAME=my_worker
      - WORKER_QUEUE=queue2
    depends_on:
      - broker

  stresser:
    build: stresser
    volumes:
      - ./src:/app
    depends_on:
      - broker

  supervisor:
    build: supervisor
    volumes:
      - ./src:/app
    depends_on:
      - broker
    ports:
      - 5555:5555

volumes:
  broker_data:
